const $=id=>document.getElementById(id);let gigs=[];
const sets={
'Web Development':[['I will build a modern responsive website for your business','business website, responsive design, web development'],['I will create a professional React website for your startup','react website, startup website, frontend'],['I will fix HTML CSS JavaScript bugs on your website','html css fix, javascript bug, website fix'],['I will convert your Figma design into a responsive website','figma to html, figma to react, responsive website'],['I will build a custom web dashboard for your business','admin dashboard, web app, dashboard ui']],
'AI Websites':[['I will build a modern AI website for your startup','ai website, ai startup, ai web app'],['I will create an AI tool landing page with a premium design','ai landing page, saas design, ai tool'],['I will build an AI chatbot interface for your website','ai chatbot, chatbot ui, ai assistant'],['I will create an AI SaaS MVP frontend','ai saas, mvp, saas frontend'],['I will build a responsive AI product website','ai product, responsive website, ai web design']],
'SaaS':[['I will build a modern SaaS landing page for your startup','saas landing page, startup, saas website'],['I will create a professional SaaS dashboard UI','saas dashboard, dashboard ui, web app'],['I will build your SaaS MVP frontend in React','saas mvp, react, web app'],['I will design a pricing page for your SaaS product','pricing page, saas, conversion'],['I will create a complete responsive SaaS website','saas website, responsive, startup']],
'Landing Pages':[['I will build a high converting landing page for your business','landing page, conversion, business website'],['I will create a modern product landing page','product landing page, modern website, startup'],['I will build a SaaS landing page with pricing and FAQ','saas landing page, pricing, faq'],['I will create a mobile first landing page','mobile website, landing page, responsive'],['I will redesign your landing page for better conversions','landing page redesign, conversion, ui']],
'Chrome Extensions':[['I will build a custom Chrome extension for your business','chrome extension, browser extension, javascript'],['I will create a professional Chrome extension popup UI','chrome extension, popup ui, frontend'],['I will turn your web idea into a Chrome extension','chrome extension, web app, automation'],['I will fix bugs in your Chrome extension','chrome extension fix, javascript, debugging'],['I will build a simple productivity Chrome extension','chrome extension, productivity, browser tool']],
'API Integration':[['I will integrate an API into your website or web app','api integration, javascript, web app'],['I will build a custom API dashboard','api dashboard, frontend, web app'],['I will connect your website to a third party API','api integration, api connection, website'],['I will create a REST API frontend interface','rest api, frontend, javascript'],['I will debug API integration errors in your app','api debugging, javascript, web development']],
'Android Apps':[['I will convert your website into a modern Android app','android app, webview, mobile app'],['I will build a simple Android app from your idea','android development, mobile app, apk'],['I will create a responsive mobile app UI','mobile app ui, android, app design'],['I will turn your web app into an installable PWA','pwa, web app, mobile'],['I will fix issues in your Android app','android bug fix, mobile app, debugging']]
};
function makeGigs(){const cat=$('category').value,count=Math.min(20,Math.max(1,+$('count').value||5)),buyer=$('buyer').value||'businesses',min=+$('minPrice').value||25,max=+$('maxPrice').value||150;const base=sets[cat];gigs=Array.from({length:count},(_,i)=>{const [title,keywords]=base[i%base.length];const extra=i>=base.length?` — ${['fast delivery','premium quality','mobile friendly','clean code','modern UI'][i%5]}`:'';const low=Math.round(min+(max-min)*(i%5)/5);const high=Math.max(low+10,Math.round(min+(max-min)*((i%5)+1)/5));return{id:i+1,title:title+extra,description:`I will deliver a clean, modern and responsive ${cat.toLowerCase()} solution tailored for ${buyer}. The project will focus on usability, professional design, mobile responsiveness and clean implementation.`,packages:{basic:`$${low}`,standard:`$${Math.round((low+high)/2)}`,premium:`$${high}`},delivery:['2 days','3 days','4 days'][i%3],revisions:[1,2,3][i%3],keywords};});render();}
function render(){const box=$('results');$('status').textContent=`${gigs.length} draft${gigs.length===1?'':'s'} ready`;if(!gigs.length){box.className='results empty';box.innerHTML='<div><strong>No gigs yet.</strong><p>Choose a category and click Generate Gigs.</p></div>';return}box.className='results';box.innerHTML=gigs.map(g=>`<article class="gig"><button class="copy" data-id="${g.id}">Copy</button><div class="gig-top"><h3>${g.title}</h3><span class="pill">${g.packages.standard}</span></div><p class="desc">${g.description}</p><div class="meta"><span>Basic ${g.packages.basic}</span><span>Standard ${g.packages.standard}</span><span>Premium ${g.packages.premium}</span><span>${g.delivery}</span><span>${g.revisions} revisions</span></div><div class="keywords">Keywords: ${g.keywords}</div></article>`).join('');document.querySelectorAll('.copy').forEach(b=>b.onclick=()=>{const g=gigs.find(x=>x.id==b.dataset.id);navigator.clipboard.writeText(`${g.title}\n\n${g.description}\n\nBasic: ${g.packages.basic}\nStandard: ${g.packages.standard}\nPremium: ${g.packages.premium}\nDelivery: ${g.delivery}\nRevisions: ${g.revisions}\nKeywords: ${g.keywords}`);b.textContent='Copied ✓';setTimeout(()=>b.textContent='Copy',1200)});}
$('generate').onclick=makeGigs;$('clear').onclick=()=>{gigs=[];render()};$('export').onclick=()=>{if(!gigs.length)return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(gigs,null,2)],{type:'application/json'}));a.download='fiverr-gigs.json';a.click();URL.revokeObjectURL(a.href)};
