const $=id=>document.getElementById(id);
const els=['apiUrl','method','authType','token','apiKeyHeader','contentType','toField','messageField','senderField','senderValue','extraFields','delay','recipients','message'].reduce((o,id)=>(o[id]=$(id),o),{});
let state={running:false,paused:false,stop:false,index:0,sent:0,failed:0,failedNumbers:[],numbers:[]};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function numbers(){return els.recipients.value.split(/[\n,;\r]+/).map(x=>x.trim()).filter(Boolean)}
function updateCounts(){state.numbers=numbers();$('recipientCount').textContent=`${state.numbers.length} numbers`; $('remaining').textContent=Math.max(0,state.numbers.length-state.index); $('progressText').textContent=`${Math.min(state.index,state.numbers.length)} / ${state.numbers.length}`; $('progressBar').style.width=(state.numbers.length?Math.min(100,state.index/state.numbers.length*100):0)+'%'; $('sent').textContent=state.sent; $('failed').textContent=state.failed; $('successRate').textContent=((state.sent+state.failed)?Math.round(state.sent/(state.sent+state.failed)*100):0)+'%'}
function log(text,type='info'){const d=document.createElement('div');d.className='log-line '+type;d.textContent=`[${new Date().toLocaleTimeString()}] ${text}`;$('log').prepend(d)}
function parseExtra(){const raw=els.extraFields.value.trim();if(!raw)return{};try{const v=JSON.parse(raw);if(!v||Array.isArray(v)||typeof v!=='object')throw 0;return v}catch{return null}}
function headers(){const h={'Accept':'application/json'};if(els.contentType.value==='application/json')h['Content-Type']='application/json';else h['Content-Type']='application/x-www-form-urlencoded';if(els.authType.value==='bearer'&&els.token.value)h.Authorization=`Bearer ${els.token.value}`;if(els.authType.value==='apiKey'&&els.token.value)h[els.apiKeyHeader.value.trim()||'X-API-Key']=els.token.value;return h}
function makeBody(to){const extra=parseExtra();if(extra===null)throw new Error('Extra JSON fields must be valid JSON');const body={...extra};body[els.toField.value.trim()||'to']=to;body[els.messageField.value.trim()||'message']=els.message.value;const sf=els.senderField.value.trim();if(sf&&els.senderValue.value.trim())body[sf]=els.senderValue.value.trim();return body}
async function request(to){const url=els.apiUrl.value.trim();if(!/^https:\/\//i.test(url))throw new Error('API URL must start with https://');const body=makeBody(to);let options={method:els.method.value,headers:headers()};if(els.contentType.value==='application/json')options.body=JSON.stringify(body);else options.body=new URLSearchParams(body).toString();const res=await fetch(url,options);const text=await res.text();if(!res.ok)throw new Error(`HTTP ${res.status}${text?`: ${text.slice(0,180)}`:''}`);return text}
function validate(){if(!els.apiUrl.value.trim())throw new Error('Enter API URL');if(!els.message.value.trim())throw new Error('Enter a message');if(!state.numbers.length)throw new Error('Add at least one recipient');if(parseExtra()===null)throw new Error('Invalid extra JSON fields')}
async function sendTest(){try{if(!els.testNumber.value.trim())throw new Error('Enter a test number');if(!els.apiUrl.value.trim())throw new Error('Enter API URL');if(!els.message.value.trim())throw new Error('Enter a message');$('testSend').disabled=true;$('testStatus').textContent='Sending...';await request(els.testNumber.value.trim());$('testStatus').textContent='Test sent successfully';log(`Test sent to ${els.testNumber.value.trim()}`,'ok')}catch(e){$('testStatus').textContent=e.message;log(`Test failed: ${e.message}`,'err')}finally{$('testSend').disabled=false}}
async function start(){try{state.numbers=numbers();validate();state.running=true;state.paused=false;state.stop=false;state.index=0;state.sent=0;state.failed=0;state.failedNumbers=[];setButtons();updateCounts();log(`Starting ${state.numbers.length} recipient(s)`);for(;state.index<state.numbers.length;state.index++){if(state.stop)break;while(state.paused&&!state.stop)await sleep(150);if(state.stop)break;const n=state.numbers[state.index];try{await request(n);state.sent++;log(`Sent: ${n}`,'ok')}catch(e){state.failed++;state.failedNumbers.push(n);log(`Failed: ${n} — ${e.message}`,'err')}updateCounts();if(state.index<state.numbers.length-1)await sleep(Math.max(0,Number(els.delay.value)||0))}state.running=false;state.paused=false;setButtons();updateCounts();log(state.stop?'Sending stopped by user':`Finished — ${state.sent} sent, ${state.failed} failed`,state.failed?'err':'ok')}catch(e){log(e.message,'err');state.running=false;setButtons()}}
function setButtons(){$('start').disabled=state.running;$('pause').disabled=!state.running;$('stop').disabled=!state.running;$('pause').textContent=state.paused?'Resume':'Pause'}
$('start').onclick=start;$('testSend').onclick=sendTest;$('pause').onclick=()=>{state.paused=!state.paused;setButtons();log(state.paused?'Paused':'Resumed')};$('stop').onclick=()=>{state.stop=true;state.paused=false};$('recipients').oninput=updateCounts;$('message').oninput=()=>{$('charCount').textContent=`${els.message.value.length} characters`;$('previewText').textContent=els.message.value||'Your message will appear here.'};$('dedupe').onclick=()=>{els.recipients.value=[...new Set(numbers())].join('\n');updateCounts();log('Duplicates removed')};$('fileInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{els.recipients.value+=(els.recipients.value.trim()?'\n':'')+r.result;updateCounts();log(`Imported ${f.name}`)};r.readAsText(f)};
$('authType').onchange=()=>{$('apiKeyHeaderLabel').classList.toggle('hidden',els.authType.value!=='apiKey')};
$('clearAll').onclick=()=>{if(state.running)return;els.recipients.value='';els.message.value='';updateCounts();$('charCount').textContent='0 characters';$('previewText').textContent='Your message will appear here.'};
$('saveProfile').onclick=()=>{const data={apiUrl:els.apiUrl.value,method:els.method.value,authType:els.authType.value,token:els.token.value,apiKeyHeader:els.apiKeyHeader.value,contentType:els.contentType.value,toField:els.toField.value,messageField:els.messageField.value,senderField:els.senderField.value,senderValue:els.senderValue.value,extraFields:els.extraFields.value,delay:els.delay.value};localStorage.setItem('smsProfile',JSON.stringify(data));log('Profile saved locally')};
$('exportFailed').onclick=()=>{if(!state.failedNumbers.length){log('No failed numbers to export');return}const blob=new Blob([state.failedNumbers.join('\n')],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='failed-numbers.txt';a.click();URL.revokeObjectURL(a.href)};
try{const p=JSON.parse(localStorage.getItem('smsProfile')||'null');if(p)Object.keys(p).forEach(k=>{if(els[k])els[k].value=p[k]??''})}catch{}updateCounts();$('charCount').textContent='0 characters';
